# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.5
loader_version=0.19.2
loom_version=1.16.2

# Mod Properties
mod_version=1.3.0
maven_group=net.hfstack.rallyguard
archives_base_name=rallyguard-fabric-1.21.11
maven_artifact_id=rally-of-the-guard

# Dependencies
fabric_version=0.141.4+1.21.11
guardvillagers_jar=guardvillagers-2.1.2-1.21.11.jar
midnightlib_version=1.9.2+1.21.11-fabric
guardvillagers_file_id=7814448
configured_file_id=7530374
modmenu_file_id=7808841
yacl_file_id=7437843
quilt_parsers_gson_version=0.2.1
junit_version=5.11.4
